services:
  web:
    build: .
    image: genplan
    restart: always
    volumes:
      - .:/app:z
      - ../src:/src:z
    environment:
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "5000:5000"
